### ISSUE TITLE
Failed to install core daily-master server in CI

### ISSUE THREAD

**Issue by saw-jan** [owncloud/litmus-testing#13]
Builds: https://drone.owncloud.com/owncloud/litmus-testing/1989/1/4

```bash
$ wget -qO- https://download.owncloud.com/server/daily/owncloud-daily-master.tar.bz2 | tar -xj -C /tmp/owncloud/ --strip 1
Fetched 10.13.2 prealpha - channel: daily - build at 2023-10-09T22:02:22+00:00 - SHA: bf51dddc58f4cfeed5e478a8183e6423076447e9
rsync -aIX   /tmp/owncloud/ /var/www/owncloud/server
/var/www/owncloud/server/apps /var/www/owncloud
testing app already available
/var/www/owncloud
installing owncloud
$ wait-for-it -t 600 mysql:3306
services are ready!
/var/www/owncloud/server /var/www/owncloud
$ php ./occ maintenance:install -vvv         --database=mysql         --database-name=owncloud         --database-table-prefix=oc_         --admin-user=admin         --admin-pass=admin         --data-dir=/var/www/owncloud/server/data --database-host=mysql                      --database-user=owncloud                      --database-pass=owncloud
An unhandled exception has been thrown:
Error: Class 'OC_Mount_Config' not found in /var/www/owncloud/server/apps/files_external/appinfo/app.php:30
Stack trace:
#0 /var/www/owncloud/server/lib/private/legacy/app.php(253): require_once()
#1 /var/www/owncloud/server/lib/private/legacy/app.php(192): OC_App::requireAppFile()
#2 /var/www/owncloud/server/lib/private/DB/MigrationService.php(103): OC_App::loadApp()
#3 /var/www/owncloud/server/lib/private/Installer.php(525): OC\DB\MigrationService->__construct()
#4 /var/www/owncloud/server/lib/private/Installer.php(499): OC\Installer::installShippedApp()
#5 /var/www/owncloud/server/lib/private/Setup.php(389): OC\Installer::installShippedApps()
#6 /var/www/owncloud/server/core/Command/Maintenance/Install.php(90): OC\Setup->install()
#7 /var/www/owncloud/server/lib/composer/symfony/console/Command/Command.php(298): OC\Core\Command\Maintenance\Install->execute()
#8 /var/www/owncloud/server/lib/composer/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#9 /var/www/owncloud/server/lib/composer/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/owncloud/server/lib/composer/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#11 /var/www/owncloud/server/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#12 /var/www/owncloud/server/console.php(94): OC\Console\Application->run()
#13 /var/www/owncloud/server/occ(11): require_once('/var/www/ownclo...')
#14 {main}
```

**Comment by phil-davis** [comment]
@DeepDiver1975 FYI
I suppose that this is related to removing `files_external/3rdparty` from core yesterday.
Do you have an idea about this?
Or should I dig into it?

**Comment by DeepDiver1975** [comment]
`OC_Mount_Config` is declared in https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php

This file/class is not autoloaded via a proper namespace setup but via an explicit composer definition https://github.com/owncloud/core/blob/3d5390721db5f19b124720e6f5bd9ce512ed498d/composer.json#L29

which is wrong - it is setup under `autoload-dev` ....


Will do a pr ....
